import React from "react";

/**
 * AIBadge - Visual indicator that a field contains AI-generated output
 * Use this component next to any field/value that was generated by the AI service
 */
const AIBadge = ({ size = "sm" }) => (
  <span className="ai-generated-badge" title="This value was generated by AI">
    🤖 AI
  </span>
);

/**
 * AIField - Wrapper for displaying an AI-generated field with label + badge
 */
export const AIField = ({ label, value, children }) => (
  <div>
    <div className="ai-field-label">
      <span>🤖</span> {label}
    </div>
    <div style={{ color: "#1e293b", fontWeight: 500 }}>
      {children || value}
    </div>
  </div>
);

/**
 * AISection - A highlighted panel containing multiple AI-generated fields
 */
export const AISection = ({ title, children }) => (
  <div className="ai-section">
    <div
      style={{
        display: "flex",
        alignItems: "center",
        gap: "8px",
        marginBottom: "16px",
      }}
    >
      <span style={{ fontSize: "1.1rem" }}>🤖</span>
      <span
        style={{
          fontWeight: 700,
          fontSize: "0.95rem",
          color: "#6d28d9",
        }}
      >
        {title || "AI Analysis Results"}
      </span>
      <span
        style={{
          fontSize: "0.7rem",
          color: "#8b5cf6",
          background: "#ede9fe",
          padding: "2px 8px",
          borderRadius: "6px",
          fontWeight: 600,
        }}
      >
        GENERATED BY AI
      </span>
    </div>
    <div
      style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
        gap: "16px",
      }}
    >
      {children}
    </div>
  </div>
);

export default AIBadge;
