const mongoose = require("mongoose");

const complaintSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    description: {
      type: String,
      required: [true, "Description is required"],
      minlength: 10,
    },
    imageUrl: {
      type: String,
      default: null,
    },

    // ============================================================
    // 🤖 AI-GENERATED FIELDS — Values below are output generated by AI
    // These fields are populated by the AI analysis service
    // ============================================================
    category: {
      type: String,
      // 🤖 AI Generated: Category of the complaint (e.g., Plumbing, Electrical, Civil)
      enum: [
        "Plumbing",
        "Electrical",
        "Civil",
        "Housekeeping",
        "IT Infrastructure",
        "Furniture",
        "Others",
      ],
      default: "Others",
    },
    priority: {
      type: String,
      // 🤖 AI Generated: Priority level determined by AI based on complaint severity
      enum: ["Low", "Medium", "High", "Critical"],
      default: "Medium",
    },
    department: {
      type: String,
      // 🤖 AI Generated: Department that should handle this complaint
      default: "General Maintenance",
    },
    estimatedResolution: {
      type: String,
      // 🤖 AI Generated: Estimated time to resolve (e.g., "2-3 days")
      default: "3-5 days",
    },
    reasoning: {
      type: String,
      // 🤖 AI Generated: AI's reasoning/explanation for its analysis
      default: "",
    },
    riskScore: {
      type: Number,
      // 🤖 AI Generated: Risk score from 0 to 100 calculated by AI
      min: 0,
      max: 100,
      default: 50,
    },
    aiAnalysisRaw: {
      type: mongoose.Schema.Types.Mixed,
      // 🤖 AI Generated: Raw complete response object returned by AI service
      default: null,
    },
    // ============================================================
    // END OF AI-GENERATED FIELDS
    // ============================================================

    status: {
      type: String,
      enum: ["Open", "Assigned", "In Progress", "Resolved", "Closed"],
      default: "Open",
    },
    assignedTo: {
      type: String,
      default: null,
    },
    assignedAt: {
      type: Date,
      default: null,
    },
    resolvedAt: {
      type: Date,
      default: null,
    },
    location: {
      type: String,
      default: "",
    },
    block: {
      type: String,
      default: "",
    },
  },
  { timestamps: true }
);

// Index for faster queries
complaintSchema.index({ userId: 1, createdAt: -1 });
complaintSchema.index({ status: 1, priority: 1 });
complaintSchema.index({ category: 1 });

module.exports = mongoose.model("Complaint", complaintSchema);
